use_frameworks!

platform :ios, '8.0'

target 'CWFlexiblePageControl_Example' do
  pod 'CWFlexiblePageControl', :path => '../'

  target 'CWFlexiblePageControl_Tests' do
    inherit! :search_paths

    
  end
end
